name: build-and-lint

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]      

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 20
        
        - name: Install Backend Dependencies
          working-directory: server
          run: npm ci
        
        - name: Lint Backend
          working-directory: server
          run: npm run lint -- --max-warnings=0

        - name: Install Frontend Dependencies
          working-directory: client
          run: npm ci
        
        - name: Lint Frontend
          working-directory: client
          run: npm run lint -- --max-warnings=0
        
        - name: Build Backend Image
          run: docker build -t backend ./server

        - name: Build Frontend Image
          run: docker build -t frontend ./client
